// Generates docs/ITEMS.md — a full, reviewable catalogue of every item, with the
// stats the engine actually infers (combat-stats.js) so balance can be eyeballed
// at a glance. Run: node scripts/dump-items.mjs
//
// Weapon "Damage" and armour "Armor/Ward" are the BASE item values AFTER tier +
// heft scaling but BEFORE the wielder's attributes/mastery — i.e. what the item
// itself contributes. In a real fight, damage further scales with the wielder's
// governing attribute and weapon mastery.

import fs from "node:fs";
import path from "node:path";
import { ALL_ITEMS } from "../src/data/catalog.js";
import { itemCombatStats, itemRequirement, weaponCategory } from "../src/engine/combat-stats.js";
import { tierLabel, tierOrder } from "../src/data/tiers.js";
import { useEffectChips } from "../src/data/goods.js";
import { perishDescriptor } from "../src/engine/spoilage.js";

const ATTR = { body: "Body", reflex: "Reflex", vigor: "Vigor", mind: "Mind", wit: "Wit", presence: "Presence" };
const items = Object.values(ALL_ITEMS);
const byTier = (a, b) => tierOrder(a.tier || "common") - tierOrder(b.tier || "common") || (a.value || 0) - (b.value || 0);
const esc = (s) => String(s ?? "").replace(/\|/g, "\\|");
const cp = (v) => (v == null ? "—" : `${v}cp`);

function reqStr(def) {
  const r = itemRequirement(def);
  return r.value > 0 ? `${ATTR[r.attr]} ${r.value}` : "—";
}

const out = [];
out.push("# Item Catalogue", "");
out.push(`_Auto-generated by \`scripts/dump-items.mjs\` — ${items.length} items. Damage/Armor are the item's BASE contribution after tier + heft scaling, before the wielder's attributes & mastery._`, "");

// ---- Weapons ----
const weapons = items.filter((d) => d.kind === "weapon").sort(byTier);
out.push(`## Weapons (${weapons.length})`, "");
out.push("| Name | id | Family | Tier | Damage | Pen | Type | Uses (attr) | Value |", "|---|---|---|---|---|---|---|---|---|");
for (const d of weapons) {
  const cs = itemCombatStats(d);
  const dmg = cs.damage ? `${cs.damage.min}–${cs.damage.max}` : "—";
  out.push(`| ${esc(d.name)} | \`${d.id}\` | ${weaponCategory(d) || "—"} | ${tierLabel(d.tier)} | ${dmg} | ${cs.damage?.pen || 0} | ${cs.damage?.type || "—"} | ${reqStr(d)} | ${cp(d.value)} |`);
}
out.push("");

// ---- Armour (body), shields, clothing, trinkets ----
function defenceTable(title, kinds) {
  const rows = items.filter((d) => kinds.includes(d.kind) && itemCombatStats(d).damage === null).sort(byTier);
  out.push(`## ${title} (${rows.length})`, "");
  out.push("| Name | id | Tier | Armor | Ward | Dodge | Req | Value |", "|---|---|---|---|---|---|---|---|");
  for (const d of rows) {
    const cs = itemCombatStats(d);
    out.push(`| ${esc(d.name)} | \`${d.id}\` | ${tierLabel(d.tier)} | ${cs.armor || 0} | ${cs.ward || 0} | ${cs.dodge || 0} | ${reqStr(d)} | ${cp(d.value)} |`);
  }
  out.push("");
}
defenceTable("Body Armour", ["armor"]);
defenceTable("Shields", ["shield"]);
defenceTable("Helms, Limbs & Cloaks (clothing)", ["clothing"]);
defenceTable("Trinkets", ["trinket"]);

// ---- Tools ----
const tools = items.filter((d) => d.kind === "tool").sort(byTier);
out.push(`## Tools (${tools.length})`, "");
out.push("| Name | id | Tier | Uses | Consumable | Value | Description |", "|---|---|---|---|---|---|---|");
for (const d of tools) {
  const t = d.tool || {};
  out.push(`| ${esc(d.name)} | \`${d.id}\` | ${tierLabel(d.tier)} | ${(t.uses || []).join(", ")} | ${t.consumable ? "yes" : "—"} | ${cp(d.value)} | ${esc(d.description)} |`);
}
out.push("");

// ---- Consumables (remedy / food / drink) ----
const cons = items.filter((d) => ["remedy", "food", "drink"].includes(d.kind)).sort((a, b) => (a.kind).localeCompare(b.kind) || (a.value || 0) - (b.value || 0));
out.push(`## Consumables (${cons.length})`, "");
out.push("| Name | id | Kind | Effect | Keeps | Value |", "|---|---|---|---|---|---|");
for (const d of cons) {
  const eff = useEffectChips(d).join(", ") || "—";
  const keeps = perishDescriptor(d) || (d.kind === "food" ? "—" : "n/a");
  out.push(`| ${esc(d.name)} | \`${d.id}\` | ${d.kind} | ${esc(eff)} | ${esc(keeps)} | ${cp(d.value)} |`);
}
out.push("");

// ---- Materials ----
const mats = items.filter((d) => d.kind === "material").sort((a, b) => (a.value || 0) - (b.value || 0));
out.push(`## Crafting Materials (${mats.length})`, "");
out.push("| Name | id | Value | Description |", "|---|---|---|---|");
for (const d of mats) out.push(`| ${esc(d.name)} | \`${d.id}\` | ${cp(d.value)} | ${esc(d.description)} |`);
out.push("");

const dir = path.resolve("docs");
fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(path.join(dir, "ITEMS.md"), out.join("\n"));
console.log(`Wrote docs/ITEMS.md — ${items.length} items (${weapons.length} weapons, ${tools.length} tools, ${cons.length} consumables, ${mats.length} materials).`);
